### ISSUE TITLE
New stache.yml does not use latest format

### ISSUE THREAD

**Issue by Blackbaud-ChristiSchneider** [blackbaud-community/stache#57]
When you create a site with `stache new my-site`, some of the fields are out of date.

Original: 

```
omnibar_title: <%= stache.config.product_name_short %>
omnibar_link: <%= stache.config.base %>
omnibar_link_enabled: true
```

New: 

```
 omnibar:
   serviceName: <%= stache.config.product_name_short %>
   serviceNameLink: <%= stache.config.base %>
   enableServiceNameLink: true
```
